import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  Sequence,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import narration from "./narration.json";

// ---- editable constants ---------------------------------------------------
const BG = "#0B1020";
const FG = "#E8ECFF";
const MUTED = "#8A93B2";
const CYAN = "#6EE7F9";
const VIOLET = "#A78BFA";
const GREEN = "#34D399";
const RED = "#F87171";
const FONT =
  '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
const MONO = '"SF Mono", "JetBrains Mono", "Consolas", monospace';

// Timing, audio and images come from narration.json, generated by
// scripts/generate-assets.mjs. Scene duration == narration length → perfect sync.
type Clip = {
  id: string;
  audio: string;
  image: string | null;
  durationInFrames: number;
};
const CLIPS = narration as Clip[];
export const DEMO_DURATION = CLIPS.reduce((a, c) => a + c.durationInFrames, 0);

// ---- helpers --------------------------------------------------------------
const Scene: React.FC<{
  dur: number;
  id?: string;
  audio?: string;
  image?: string | null;
  children: React.ReactNode;
  bg?: string;
}> = ({ dur, id, audio, image, children, bg = BG }) => {
  const frame = useCurrentFrame();
  const inOpacity = interpolate(frame, [0, 14], [0, 1], {
    extrapolateRight: "clamp",
  });
  const outOpacity = interpolate(frame, [dur - 14, dur], [1, 0], {
    extrapolateLeft: "clamp",
  });
  // slow Ken-Burns drift so the illustration feels alive
  const scale = interpolate(frame, [0, dur], [1.08, 1.16]);
  return (
    <AbsoluteFill
      style={{
        backgroundColor: bg,
        opacity: Math.min(inOpacity, outOpacity),
        fontFamily: FONT,
        color: FG,
      }}
    >
      {audio ? <Audio src={staticFile(audio)} /> : null}
      {image ? (
        <AbsoluteFill>
          <Img
            src={staticFile(image)}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
              transform: `scale(${scale})`,
              opacity: 0.4,
            }}
          />
          <AbsoluteFill
            style={{
              background:
                "radial-gradient(closest-side, rgba(11,16,32,0.30), rgba(11,16,32,0.88))",
            }}
          />
        </AbsoluteFill>
      ) : id ? (
        <SceneArt id={id} />
      ) : null}
      <Glow />
      {children}
    </AbsoluteFill>
  );
};

const Glow: React.FC = () => (
  <AbsoluteFill
    style={{
      background: `radial-gradient(900px 600px at 20% 10%, rgba(110,231,249,0.10), transparent 60%),
                   radial-gradient(900px 600px at 85% 90%, rgba(167,139,250,0.10), transparent 60%)`,
    }}
  />
);

const useRise = (delay = 0, mass = 0.6) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const s = spring({
    frame: frame - delay,
    fps,
    config: { damping: 200, mass },
  });
  return {
    opacity: s,
    transform: `translateY(${interpolate(s, [0, 1], [24, 0])}px)`,
  };
};

const Kicker: React.FC<{ children: React.ReactNode; delay?: number }> = ({
  children,
  delay = 0,
}) => {
  const r = useRise(delay);
  return (
    <div
      style={{
        ...r,
        letterSpacing: 6,
        textTransform: "uppercase",
        fontSize: 22,
        fontWeight: 600,
        color: CYAN,
      }}
    >
      {children}
    </div>
  );
};

// ---- Scene 1: Title -------------------------------------------------------
const TitleScene: React.FC = () => {
  const frame = useCurrentFrame();
  const t1 = useRise(8);
  const t2 = useRise(20);
  const tag = useRise(40);
  const count = Math.round(
    interpolate(frame, [40, 95], [0, 100000], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }),
  );
  return (
    <AbsoluteFill
      style={{ justifyContent: "center", alignItems: "center", gap: 14 }}
    >
      <Kicker delay={0}>Redrob · Intelligent Candidate Ranking</Kicker>
      <div style={{ ...t1, fontSize: 96, fontWeight: 800, letterSpacing: -2 }}>
        Recruiter-Brain
      </div>
      <div
        style={{
          ...t2,
          fontSize: 64,
          fontWeight: 300,
          marginTop: -18,
          color: MUTED,
        }}
      >
        Candidate Ranker
      </div>
      <div
        style={{
          ...tag,
          marginTop: 34,
          fontSize: 30,
          display: "flex",
          gap: 18,
          alignItems: "baseline",
        }}
      >
        <span style={{ color: MUTED }}>Top 100 of</span>
        <span
          style={{
            fontFamily: MONO,
            fontSize: 44,
            fontWeight: 700,
            color: CYAN,
            minWidth: 220,
            textAlign: "right",
            display: "inline-block",
          }}
        >
          {count.toLocaleString()}
        </span>
      </div>
      <div style={{ ...tag, marginTop: 18, display: "flex", gap: 14 }}>
        {["CPU-only", "< 5 min", "no network"].map((c) => (
          <Pill key={c}>{c}</Pill>
        ))}
      </div>
    </AbsoluteFill>
  );
};

const Pill: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <span
    style={{
      border: `1px solid ${VIOLET}55`,
      background: `${VIOLET}1A`,
      color: FG,
      padding: "8px 18px",
      borderRadius: 999,
      fontSize: 22,
      fontWeight: 500,
    }}
  >
    {children}
  </span>
);

// ---- Scene 2: Problem -----------------------------------------------------
const Bar: React.FC<{
  label: string;
  value: number;
  max: number;
  color: string;
  delay: number;
}> = ({ label, value, max, color, delay }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const grow = spring({ frame: frame - delay, fps, config: { damping: 200 } });
  const w = (value / max) * 100 * grow;
  const shown = Math.round(value * grow);
  return (
    <div style={{ width: 980 }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          fontSize: 26,
          marginBottom: 8,
        }}
      >
        <span style={{ color: MUTED }}>{label}</span>
        <span style={{ fontFamily: MONO, color }}>
          {shown.toLocaleString()}
        </span>
      </div>
      <div
        style={{
          height: 34,
          background: "#1A2238",
          borderRadius: 8,
          overflow: "hidden",
        }}
      >
        <div
          style={{
            width: `${w}%`,
            height: "100%",
            background: color,
            borderRadius: 8,
          }}
        />
      </div>
    </div>
  );
};

const ProblemScene: React.FC = () => {
  const head = useRise(6);
  const ratio = useRise(90);
  return (
    <AbsoluteFill
      style={{
        justifyContent: "center",
        alignItems: "center",
        gap: 40,
        padding: 80,
      }}
    >
      <div style={{ textAlign: "center" }}>
        <Kicker>The real problem isn't search</Kicker>
        <div style={{ ...head, fontSize: 52, fontWeight: 700, marginTop: 14 }}>
          Keyword matching ranks the people the JD rejects
        </div>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 30 }}>
        <Bar
          label="Carry 3+ relevant skills"
          value={8545}
          max={8545}
          color={RED}
          delay={20}
        />
        <Bar
          label="…with a corroborating title"
          value={755}
          max={8545}
          color={GREEN}
          delay={55}
        />
      </div>
      <div
        style={{
          ...ratio,
          fontSize: 34,
          fontWeight: 600,
          color: FG,
        }}
      >
        ≈ <span style={{ color: RED }}>10:1</span> keyword-stuffer noise —{" "}
        <span style={{ color: MUTED }}>
          "has the skills" isn't discriminative
        </span>
      </div>
    </AbsoluteFill>
  );
};

// ---- Scene 3: Rubric ------------------------------------------------------
const Branch: React.FC<{
  title: string;
  sub: string;
  color: string;
  delay: number;
}> = ({ title, sub, color, delay }) => {
  const r = useRise(delay);
  return (
    <div
      style={{
        ...r,
        width: 380,
        padding: "26px 28px",
        borderRadius: 18,
        background: "#121A30",
        border: `1px solid ${color}44`,
      }}
    >
      <div style={{ fontSize: 30, fontWeight: 700, color }}>{title}</div>
      <div style={{ fontSize: 22, color: MUTED, marginTop: 8 }}>{sub}</div>
    </div>
  );
};

const RubricScene: React.FC = () => {
  const card = useRise(8, 0.8);
  return (
    <AbsoluteFill
      style={{ justifyContent: "center", alignItems: "center", gap: 56 }}
    >
      <Kicker>The signature move</Kicker>
      <div
        style={{
          ...card,
          fontFamily: MONO,
          fontSize: 40,
          fontWeight: 700,
          padding: "22px 40px",
          borderRadius: 16,
          background: `linear-gradient(135deg, ${CYAN}22, ${VIOLET}22)`,
          border: `1px solid ${CYAN}66`,
        }}
      >
        rubric.yaml
      </div>
      <div style={{ fontSize: 24, color: MUTED, marginTop: -32 }}>
        One human-reviewed JD-understanding layer drives three things at once
      </div>
      <div style={{ display: "flex", gap: 30 }}>
        <Branch
          title="Ranking"
          sub="what the role actually rewards"
          color={CYAN}
          delay={36}
        />
        <Branch
          title="Honeypot avoidance"
          sub="internal-consistency rules"
          color={VIOLET}
          delay={52}
        />
        <Branch
          title="Reasoning"
          sub="every clause traces to a fact"
          color={GREEN}
          delay={68}
        />
      </div>
    </AbsoluteFill>
  );
};

// ---- Scene 4: Architecture ------------------------------------------------
const Col: React.FC<{
  title: string;
  meta: string;
  lines: string[];
  color: string;
  delay: number;
}> = ({ title, meta, lines, color, delay }) => {
  const r = useRise(delay, 0.8);
  return (
    <div
      style={{
        ...r,
        width: 560,
        padding: 36,
        borderRadius: 20,
        background: "#0F1730",
        border: `1px solid ${color}55`,
      }}
    >
      <div style={{ fontSize: 30, fontWeight: 800, color }}>{title}</div>
      <div style={{ fontSize: 20, color: MUTED, marginBottom: 22 }}>{meta}</div>
      {lines.map((l, i) => (
        <div
          key={i}
          style={{
            fontFamily: MONO,
            fontSize: 22,
            color: FG,
            padding: "10px 0",
            borderTop: i ? `1px solid #1E2740` : "none",
          }}
        >
          {l}
        </div>
      ))}
    </div>
  );
};

const ArchScene: React.FC = () => {
  const arrow = useRise(70);
  const note = useRise(95);
  return (
    <AbsoluteFill
      style={{ justifyContent: "center", alignItems: "center", gap: 40 }}
    >
      <Kicker>Intelligence offline · rank-time fast &amp; model-free</Kicker>
      <div
        style={{ display: "flex", alignItems: "center", gap: 28, marginTop: 8 }}
      >
        <Col
          title="OFFLINE"
          meta="network OK · no clock"
          lines={[
            "JD ──LLM──▶ rubric.yaml",
            "candidates ─▶ features.parquet",
            "42 raw signals + TF-IDF",
          ]}
          color={VIOLET}
          delay={14}
        />
        <div style={{ ...arrow, fontSize: 56, color: CYAN }}>▶</div>
        <Col
          title="RANK TIME"
          meta="≤5 min · CPU · no net"
          lines={[
            "load rubric.yaml",
            "score = weighted sum",
            "sort ─▶ top 100 ─▶ reasons",
          ]}
          color={CYAN}
          delay={40}
        />
      </div>
      <div style={{ ...note, fontSize: 26, color: MUTED }}>
        No model loaded at rank time →{" "}
        <span style={{ color: GREEN }}>the 5-min budget is never at risk</span>
      </div>
    </AbsoluteFill>
  );
};

// ---- Scene 5: Results -----------------------------------------------------
const Metric: React.FC<{
  value: string;
  label: string;
  color: string;
  delay: number;
}> = ({ value, label, color, delay }) => {
  const r = useRise(delay, 0.7);
  return (
    <div
      style={{
        ...r,
        width: 420,
        padding: "40px 30px",
        borderRadius: 22,
        background: "#101A33",
        border: `1px solid ${color}55`,
        textAlign: "center",
      }}
    >
      <div
        style={{
          fontFamily: MONO,
          fontSize: 72,
          fontWeight: 800,
          color,
          lineHeight: 1,
        }}
      >
        {value}
      </div>
      <div style={{ fontSize: 24, color: MUTED, marginTop: 18 }}>{label}</div>
    </div>
  );
};

const ResultsScene: React.FC = () => {
  const frame = useCurrentFrame();
  const ndcg = interpolate(frame, [16, 70], [0, 0.9968], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  }).toFixed(4);
  return (
    <AbsoluteFill
      style={{ justifyContent: "center", alignItems: "center", gap: 56 }}
    >
      <div style={{ textAlign: "center" }}>
        <Kicker>We built our own evaluation — no leaderboard</Kicker>
        <div style={{ fontSize: 50, fontWeight: 700, marginTop: 12 }}>
          Saturated, robust, honest
        </div>
      </div>
      <div style={{ display: "flex", gap: 30 }}>
        <Metric value={ndcg} label="Subset NDCG@10" color={CYAN} delay={14} />
        <Metric
          value="0%"
          label="Top-100 honeypot rate (pool has 40)"
          color={GREEN}
          delay={40}
        />
        <Metric
          value="100/100"
          label="domain-corroborated · YoE median 6.6"
          color={VIOLET}
          delay={66}
        />
      </div>
    </AbsoluteFill>
  );
};

// ---- Scene 6: Outro -------------------------------------------------------
const OutroScene: React.FC = () => {
  const frame = useCurrentFrame();
  const cmd =
    "python rank.py --candidates ./candidates.jsonl --out ./submission.csv";
  const chars = Math.round(
    interpolate(frame, [20, 80], [0, cmd.length], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }),
  );
  const line = useRise(6);
  const blink = Math.floor(frame / 15) % 2 === 0;
  return (
    <AbsoluteFill
      style={{ justifyContent: "center", alignItems: "center", gap: 40 }}
    >
      <div
        style={{ ...line, fontSize: 46, fontWeight: 700, textAlign: "center" }}
      >
        We built a <span style={{ color: CYAN }}>system</span>, not a prompt.
      </div>
      <div
        style={{
          fontFamily: MONO,
          fontSize: 24,
          background: "#0A0F22",
          border: "1px solid #1E2740",
          borderRadius: 14,
          padding: "22px 30px",
          color: GREEN,
          maxWidth: 1200,
        }}
      >
        <span style={{ color: MUTED }}>$ </span>
        {cmd.slice(0, chars)}
        <span style={{ opacity: blink ? 1 : 0, color: FG }}>▌</span>
      </div>
      <div style={{ fontSize: 22, color: MUTED }}>
        100 ranked · reasons from real facts · fully reproducible
      </div>
    </AbsoluteFill>
  );
};

// ---- Vector illustrations (zero-API fallback for AI images) ---------------
const ArtWrap: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const frame = useCurrentFrame();
  const float = Math.sin(frame / 40) * 10;
  return (
    <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
      <svg
        width={1300}
        height={1300}
        viewBox="0 0 1000 1000"
        style={{ opacity: 0.5, transform: `translateY(${float}px)` }}
      >
        {children}
      </svg>
      <AbsoluteFill
        style={{
          background:
            "radial-gradient(closest-side, rgba(11,16,32,0.35), rgba(11,16,32,0.82))",
        }}
      />
    </AbsoluteFill>
  );
};

// title — neural network forming a brain
const BrainArt: React.FC = () => {
  const frame = useCurrentFrame();
  const nodes = React.useMemo(() => {
    const pts: { x: number; y: number; r: number }[] = [];
    const rings = [
      { count: 1, rad: 0 },
      { count: 6, rad: 120 },
      { count: 12, rad: 230 },
      { count: 16, rad: 340 },
    ];
    rings.forEach((ring, ri) =>
      Array.from({ length: ring.count }).forEach((_, i) => {
        const a = (i / ring.count) * Math.PI * 2 + ri * 0.4;
        pts.push({
          x: 500 + Math.cos(a) * ring.rad,
          y: 500 + Math.sin(a) * ring.rad * 0.85,
          r: 6 + ((i * 7 + ri * 3) % 5),
        });
      }),
    );
    return pts;
  }, []);
  return (
    <ArtWrap>
      {nodes.map((n, i) =>
        nodes
          .slice(i + 1)
          .filter((m) => Math.hypot(m.x - n.x, m.y - n.y) < 180)
          .map((m, j) => (
            <line
              key={`${i}-${j}`}
              x1={n.x}
              y1={n.y}
              x2={m.x}
              y2={m.y}
              stroke={CYAN}
              strokeWidth={1}
              opacity={0.12 + 0.1 * Math.sin(frame / 12 + i)}
            />
          )),
      )}
      {nodes.map((n, i) => {
        const pulse = 1 + 0.25 * Math.sin(frame / 10 + i * 0.6);
        return (
          <circle
            key={i}
            cx={n.x}
            cy={n.y}
            r={n.r * pulse}
            fill={i % 3 === 0 ? VIOLET : CYAN}
            opacity={0.85}
          />
        );
      })}
    </ArtWrap>
  );
};

// problem — a field of resumes, few corroborated (green), most noise (dim/red)
const DocFieldArt: React.FC = () => {
  const frame = useCurrentFrame();
  const cols = 14;
  const rows = 8;
  const green = new Set([17, 31, 52, 66, 81, 95, 40]);
  return (
    <ArtWrap>
      {Array.from({ length: cols * rows }).map((_, i) => {
        const cx = 110 + (i % cols) * 60;
        const cy = 150 + Math.floor(i / cols) * 90;
        const isGreen = green.has(i);
        const wave = 0.25 + 0.2 * Math.sin(frame / 9 - (i % cols) * 0.5);
        return (
          <g key={i} opacity={isGreen ? 0.95 : wave}>
            <rect
              x={cx}
              y={cy}
              width={40}
              height={56}
              rx={5}
              fill={isGreen ? "#0F2A22" : "#141B2E"}
              stroke={isGreen ? GREEN : RED}
              strokeWidth={isGreen ? 2.5 : 1}
            />
            <line
              x1={cx + 7}
              y1={cy + 14}
              x2={cx + 33}
              y2={cy + 14}
              stroke={isGreen ? GREEN : MUTED}
              strokeWidth={2}
            />
            <line
              x1={cx + 7}
              y1={cy + 26}
              x2={cx + 28}
              y2={cy + 26}
              stroke={MUTED}
              strokeWidth={2}
            />
            <line
              x1={cx + 7}
              y1={cy + 38}
              x2={cx + 31}
              y2={cy + 38}
              stroke={MUTED}
              strokeWidth={2}
            />
          </g>
        );
      })}
    </ArtWrap>
  );
};

// rubric — a blueprint document branching into three rules
const BlueprintArt: React.FC = () => {
  const frame = useCurrentFrame();
  const draw = interpolate(frame % 120, [0, 60], [0, 1], {
    extrapolateRight: "clamp",
  });
  const branches = [
    { x: 280, c: CYAN },
    { x: 500, c: VIOLET },
    { x: 720, c: GREEN },
  ];
  return (
    <ArtWrap>
      <rect
        x={360}
        y={150}
        width={280}
        height={200}
        rx={16}
        fill="#101A33"
        stroke={CYAN}
        strokeWidth={2}
      />
      {[0, 1, 2, 3].map((i) => (
        <line
          key={i}
          x1={390}
          y1={195 + i * 38}
          x2={610 - (i % 2) * 50}
          y2={195 + i * 38}
          stroke={i === 0 ? CYAN : MUTED}
          strokeWidth={4}
          opacity={0.8}
        />
      ))}
      {branches.map((b, i) => (
        <g key={i}>
          <path
            d={`M 500 350 C 500 430, ${b.x} 430, ${b.x} 520`}
            fill="none"
            stroke={b.c}
            strokeWidth={2.5}
            strokeDasharray={300}
            strokeDashoffset={300 * (1 - draw)}
            opacity={0.8}
          />
          <circle
            cx={b.x}
            cy={560}
            r={34}
            fill="#101A33"
            stroke={b.c}
            strokeWidth={2.5}
            opacity={0.9 * draw + 0.1}
          />
        </g>
      ))}
    </ArtWrap>
  );
};

// arch — two pipelines with flowing packets
const PipelineArt: React.FC = () => {
  const frame = useCurrentFrame();
  const dots = 6;
  const col = (x: number, color: string, dir: number) => (
    <g>
      <rect
        x={x - 50}
        y={200}
        width={100}
        height={520}
        rx={18}
        fill="#0F1730"
        stroke={color}
        strokeWidth={2}
      />
      {Array.from({ length: dots }).map((_, i) => {
        const t = (((frame * 3 * dir + (i * 520) / dots) % 520) + 520) % 520;
        return (
          <circle
            key={i}
            cx={x}
            cy={200 + t}
            r={9}
            fill={color}
            opacity={0.9}
          />
        );
      })}
    </g>
  );
  return (
    <ArtWrap>
      {col(280, VIOLET, 1)}
      {col(720, CYAN, 1)}
      <path
        d="M 340 460 L 650 460"
        stroke={CYAN}
        strokeWidth={3}
        markerEnd="url(#ah)"
        opacity={0.8}
      />
      <defs>
        <marker
          id="ah"
          markerWidth="12"
          markerHeight="12"
          refX="8"
          refY="6"
          orient="auto"
        >
          <path d="M0,0 L10,6 L0,12 Z" fill={CYAN} />
        </marker>
      </defs>
    </ArtWrap>
  );
};

// results — rising chart with a checkmark
const ChartArt: React.FC = () => {
  const frame = useCurrentFrame();
  const pts = [
    [180, 720],
    [330, 640],
    [480, 660],
    [630, 470],
    [780, 300],
  ];
  const prog = interpolate(frame, [10, 70], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const total = pts.length - 1;
  const shown = pts.filter((_, i) => i / total <= prog + 0.001);
  const path = shown
    .map((p, i) => `${i ? "L" : "M"} ${p[0]} ${p[1]}`)
    .join(" ");
  const checkDraw = interpolate(frame, [60, 90], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  return (
    <ArtWrap>
      <line
        x1={150}
        y1={760}
        x2={850}
        y2={760}
        stroke={MUTED}
        strokeWidth={2}
      />
      <line
        x1={150}
        y1={760}
        x2={150}
        y2={250}
        stroke={MUTED}
        strokeWidth={2}
      />
      {pts.map((p, i) => (
        <rect
          key={i}
          x={p[0] - 22}
          y={p[1]}
          width={44}
          height={760 - p[1]}
          rx={6}
          fill={CYAN}
          opacity={0.12}
        />
      ))}
      <path
        d={path}
        fill="none"
        stroke={CYAN}
        strokeWidth={5}
        strokeLinejoin="round"
        strokeLinecap="round"
      />
      {shown.map((p, i) => (
        <circle key={i} cx={p[0]} cy={p[1]} r={8} fill={CYAN} />
      ))}
      <g transform="translate(700,250)">
        <circle
          r={70}
          fill="#0F2A22"
          stroke={GREEN}
          strokeWidth={4}
          opacity={0.9}
        />
        <path
          d="M -30 4 L -8 28 L 34 -24"
          fill="none"
          stroke={GREEN}
          strokeWidth={9}
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeDasharray={120}
          strokeDashoffset={120 * (1 - checkDraw)}
        />
      </g>
    </ArtWrap>
  );
};

// outro — expanding success rings
const RingsArt: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <ArtWrap>
      {[0, 1, 2, 3].map((i) => {
        const t = ((frame / 2 + i * 45) % 180) / 180;
        return (
          <circle
            key={i}
            cx={500}
            cy={500}
            r={60 + t * 380}
            fill="none"
            stroke={i % 2 ? CYAN : GREEN}
            strokeWidth={3}
            opacity={(1 - t) * 0.7}
          />
        );
      })}
      <circle
        cx={500}
        cy={500}
        r={56}
        fill="#0F2A22"
        stroke={GREEN}
        strokeWidth={4}
      />
      <path
        d="M 470 500 L 492 524 L 534 476"
        fill="none"
        stroke={GREEN}
        strokeWidth={9}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </ArtWrap>
  );
};

const ART: Record<string, React.FC> = {
  title: BrainArt,
  problem: DocFieldArt,
  rubric: BlueprintArt,
  arch: PipelineArt,
  results: ChartArt,
  outro: RingsArt,
};

const SceneArt: React.FC<{ id: string }> = ({ id }) => {
  const Comp = ART[id];
  return Comp ? <Comp /> : null;
};

// ---- Root composition -----------------------------------------------------
const SCENES: Record<string, React.FC> = {
  title: TitleScene,
  problem: ProblemScene,
  rubric: RubricScene,
  arch: ArchScene,
  results: ResultsScene,
  outro: OutroScene,
};

export const Demo: React.FC = () => {
  let from = 0;
  return (
    <AbsoluteFill style={{ backgroundColor: BG }}>
      {CLIPS.map((clip) => {
        const Comp = SCENES[clip.id];
        const node = (
          <Sequence
            key={clip.id}
            from={from}
            durationInFrames={clip.durationInFrames}
          >
            <Scene
              dur={clip.durationInFrames}
              id={clip.id}
              audio={clip.audio}
              image={clip.image}
            >
              <Comp />
            </Scene>
          </Sequence>
        );
        from += clip.durationInFrames;
        return node;
      })}
    </AbsoluteFill>
  );
};
